### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by BumbleAd** [hjkcai/swc-plugin-add-display-name#2] opened 2023-07-31 18:44 UTC
Hey
I'm trying to run build with swc and failing with following error.
"@swc/core": "^1.3.42"

My .swcrc:
```{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": true,
      "privateMethod": false,
      "functionBind": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "topLevelAwait": false,
      "importMeta": false
    },
    "loose": false,
    "keepClassNames": false,
    "target": "es2015",
    "externalHelpers": true,
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "experimental": {
      "plugins": [
        ["swc-plugin-add-display-name", {}]
      ]
    }
  }
}
```
 
Error content: 
```
[build-pure                 ] Creating an optimized production build...
[build-pure                 ] thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/feihua/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67
[build-pure                 ] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[build-pure                 ] thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/maxim.m/IdeaProjects/products/ads-console/ads-console-frontend/src/main/webapp/src/index.js")'
[build-pure                 ]
[build-pure                 ] Caused by:
[build-pure                 ]     0: failed to invoke `swc-plugin-add-display-name` as js transform plugin at node_modules/swc-plugin-add-display-name/target/wasm32-wasi/release/swc_plugin_add_display_name.wasm
[build-pure                 ]     1: RuntimeError: unreachable
[build-pure                 ]            at <unnamed> (<module>[501]:0x58431)
[build-pure                 ]            at <unnamed> (<module>[463]:0x57226)
[build-pure                 ]            at <unnamed> (<module>[508]:0x58b01)
[build-pure                 ]            at <unnamed> (<module>[507]:0x58a37)
[build-pure                 ]            at <unnamed> (<module>[376]:0x4c670)
[build-pure                 ]            at <unnamed> (<module>[17]:0x1202)
[build-pure                 ]            at <unnamed> (<module>[16]:0x11b5)
[build-pure                 ]            at <unnamed> (<module>[110]:0x20268)
[build-pure                 ]            at <unnamed> (<module>[107]:0x1c27f)
[build-pure                 ]            at <unnamed> (<module>[133]:0x2c2d7)
[build-pure                 ]            at <unnamed> (<module>[39]:0x62d2)
[build-pure                 ]            at <unnamed> (<module>[329]:0x49382)
[build-pure                 ]            at <unnamed> (<module>[648]:0x6158a)
[build-pure                 ]     2: unreachable
[build-pure                 ]
[build-pure                 ] Stack backtrace:
[build-pure                 ]    0: _napi_register_module_v1
[build-pure                 ]    1: _wasmer_vm_raise_trap
[build-pure                 ]    2: _napi_register_module_v1
[build-pure                 ]    3: _napi_register_module_v1
[build-pure                 ]    4: _napi_register_module_v1
[build-pure                 ]    5: _napi_register_module_v1
[build-pure                 ]    6: _napi_register_module_v1
[build-pure                 ]    7: _napi_register_module_v1
[build-pure                 ]    8: <unknown>
[build-pure                 ]    9: _worker
[build-pure                 ]   10: __pthread_start', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.255.18/src/plugin.rs:228:14
[build-pure                 ] stack backtrace:
[build-pure                 ]    0:        0x88ff17dd7 - _napi_register_module_v1
[build-pure                 ]    1:        0x88fbd893a - <unknown>
[build-pure                 ]    2:        0x88feeb04c - _napi_register_module_v1
[build-pure                 ]    3:        0x88ff1880b - _napi_register_module_v1
[build-pure                 ]    4:        0x88ff19052 - _napi_register_module_v1
[build-pure                 ]    5:        0x88ff18b44 - _napi_register_module_v1
[build-pure                 ]    6:        0x88ff18aa8 - _napi_register_module_v1
[build-pure                 ]    7:        0x88ff18a72 - _napi_register_module_v1
[build-pure                 ]    8:        0x891255673 - _wasmer_vm_raise_trap
[build-pure                 ]    9:        0x8912558d5 - _wasmer_vm_raise_trap
[build-pure                 ]   10:        0x8900df401 - _napi_register_module_v1
[build-pure                 ]   11:        0x88ff3059a - _napi_register_module_v1
[build-pure                 ]   12:        0x890015e91 - _napi_register_module_v1
[build-pure                 ]   13:        0x890014fa9 - _napi_register_module_v1
[build-pure                 ]   14:        0x88f92b522 - <unknown>
[build-pure                 ]   15:        0x1010abd7a - _worker
[build-pure                 ]   16:     0x7ff80ef2b259 - __pthread_start
[build-pure                 ] Failed to compile.
[build-pure                 ]
[build-pure                 ] Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/maxim.m/IdeaProjects/products/ads-console/ads-console-frontend/src/main/webapp/src/index.js")'
[build-pure                 ] Caused by:
[build-pure                 ]     0: failed to invoke `swc-plugin-add-display-name` as js transform plugin at node_modules/swc-plugin-add-display-name/target/wasm32-wasi/release/swc_plugin_add_display_name.wasm
[build-pure                 ]     1: RuntimeError: unreachable
[build-pure                 ]            at <unnamed> (<module>[501]:0x58431)
[build-pure                 ]            at <unnamed> (<module>[463]:0x57226)
[build-pure                 ]            at <unnamed> (<module>[508]:0x58b01)
[build-pure                 ]            at <unnamed> (<module>[507]:0x58a37)
[build-pure                 ]            at <unnamed> (<module>[376]:0x4c670)
[build-pure                 ]            at <unnamed> (<module>[17]:0x1202)
[build-pure                 ]            at <unnamed> (<module>[16]:0x11b5)
[build-pure                 ]            at <unnamed> (<module>[110]:0x20268)
[build-pure                 ]            at <unnamed> (<module>[107]:0x1c27f)
[build-pure                 ]            at <unnamed> (<module>[133]:0x2c2d7)
[build-pure                 ]            at <unnamed> (<module>[39]:0x62d2)
[build-pure                 ]            at <unnamed> (<module>[329]:0x49382)
[build-pure                 ]            at <unnamed> (<module>[648]:0x6158a)
[build-pure                 ]     2: unreachable
[build-pure                 ]
[build-pure                 ] Stack backtrace:
[build-pure                 ]    0: _napi_register_module_v1
[build-pure                 ]    1: _wasmer_vm_raise_trap
[build-pure                 ]    2: _napi_register_module_v1
[build-pure                 ]    3: _napi_register_module_v1
[build-pure                 ]    4: _napi_register_module_v1
[build-pure                 ]    5: _napi_register_module_v1
[build-pure                 ]    6: _napi_register_module_v1
[build-pure                 ]    7: _napi_register_module_v1
[build-pure                 ]    8: <unknown>
[build-pure                 ]    9: _worker
[build-pure                 ]   10: __pthread_start
[build-pure                 ]
[build-pure                 ] Stack backtrace:
[build-pure                 ]    0: _napi_register_module_v1
[build-pure                 ]    1: _wasmer_vm_raise_trap
[build-pure                 ]    2: <unknown>
[build-pure                 ]    3: _worker
[build-pure                 ]    4: __pthread_start
[build-pure                 ]
[build-pure                 ]
[build-pure                 ]  ELIFECYCLE  Command failed with exit code 1.
[check-circular-dependencies]  ELIFECYCLE  Command failed.
[stylelint                  ]  ELIFECYCLE  Command failed.
[lint                       ]  ELIFECYCLE  Command failed.
ERROR: "build-pure" exited with 1.
```
Is anybody familiar with this issue?

**Comment by hjkcai** [comment] 2023-08-05 15:30
This plugin requires `@swc/core@^1.3.58`, which is higher than your local version. Try upgrade `@swc/core`.

**Comment by BumbleAd** [comment] 2023-08-10 19:21
I updated swc/core to latest version @swc/core@^1.3.76
And now it fails to compile very simple scenarios

The compilation fails only when config of swc-plugin-add-display-name plugin exists

[See examples](https://play.swc.rs/?version=1.3.76&code=H4sIAAAAAAAAA8tJLVFI1FFIsubSSFSwt1dI0rTX09CE8BSSFKwU8kpzcpDEQCow5YEiAINqR2BJAAAA&config=H4sIAAAAAAAAA32SSW7DMAxF9zmFoXV8ge6aDmiBthcIuiBkOlWqCSSVOAh898pTEidtV5b%2B%2B6b4KR0XRaG2rNVdcczLvIlAjHTaZ4UPXqDJikLtgDWZKGo50S13SCjhSaoOHpzRry4GkmsYyexA8B3lK1QZ1mD5TOvktZjgV8bfQmy6go9YQ7LyTMH94fgAhxxB46%2BeCnUgkED8D1phHQifmjHB3CYhvuEO7f0ezC01feycDybUk3YwKBsC4%2Fwn9Y0YHyww951fQQHaoPTjZ4%2FNNPqcVZA82Be0Efsw5zkrIfCcI7jLiyQELRdCJyUvxnX9KEgSHIjRasTtrO88WqRszW%2FBXhaNNm2M745fn8quFe91OZASqqqsDEcLhzK%2FC1TL4th%2Bjt7h253ULtrFD7PTsvOOAgAA)

**Comment by hjkcai** [comment] 2023-08-15 01:35
I cannot reproduce from the link you provided, nor from my local machine. Could you please provide a minimal reproduction repository, or share more details?

![image](https://github.com/hjkcai/swc-plugin-add-display-name/assets/731326/bb013104-8d21-4249-8da9-23de909a4272)

**Comment by BumbleAd** [comment] 2023-09-03 13:37
I created a sandbox with the same error that I have i my code.
The failure happens in transformation of `a?.testProp` code.

https://codesandbox.io/p/sandbox/green-silence-6z7yg7?welcome=true

**Comment by hjkcai** [comment] 2023-09-15 03:43
Sorry for the late reply. I think this is an issue of swc itself.

I figured out this minimal reproduction code and `swcrc` config:

```js
function App() {
  const b = a?.testProp || "";
  return <div />
}
```

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "esnext",
    "experimental": {
      "plugins": [
        ["swc-plugin-add-display-name", {}]
      ]
    }
  }
}
```

I got this result:

```js
function App() {
    const b = this?.;
    return /*#__PURE__*/ React.createElement("div", null);
}
App.displayName = "App";
```

Apparently the optional chaining is incorrectly transformed.

However when I put this code into my unit test, it just works. Considering that swc have a lot of built-in transformations, maybe it's the issue of some of these transformations.

**Comment by hjkcai** [comment] 2023-09-15 03:47
Note that I have swc 1.3.35 and swc-plugin-add-display-name 0.1.2 in my production project and they work fine.

**Comment by BumbleAd** [comment] 2023-09-20 10:48
@hjkcai same issue also without `next`

**Comment by BumbleAd** [comment] 2023-10-05 07:12
Hi @hjkcai 
I've updated swc-plugin-add-display-name to "^0.2.3" version and looks like it is still not work.

Any chance you can help with solving this issue?

**Comment by tomchentw** [comment] 2023-10-05 09:22
@BumbleAd I had tried the code sandbox you provided with "^0.2.3" version and it still failed at the optional chaining operator. I honestly couldn't quite figure out why. In the moment I had to move away from using the optional chaining operator. :(

**Comment by hjkcai** [comment] 2023-10-18 05:12
@BumbleAd @mindplay-dk I have published version 0.3.0 of this plugin. It seems to work fine on my machine in my newly created next project with `next@13.5.5`.

Please try the new version!

**Comment by hjkcai** [comment] 2023-10-18 05:19
Note that you have to upgrade @swc/core to `^1.3.81` as [documented here](https://swc.rs/docs/plugin/selecting-swc-core) because I have upgraded the rust swc_core to `0.82.*`.

However nextjs version is not documented. I have tested roughly on `13.4.19` and `13.5.5` and worked.

**Comment by BumbleAd** [comment] 2023-10-18 13:27
@hjkcai 
Seems that the build is passed, but I found some unexpected functionality that is breaking my app business logic.

For the following code, after compilation `obj` will receive an unexpected `displayName` property.
Is it possible to avoid this addition?

`
const TestComponent = () => {
  return <div>SIMPLE COMPONENT</div>;
};

const obj = {
  PLAY: {
    prop1: "aaaa",
    comp: <TestComponent />,
  },
};
`

[Code Snippet](https://codesandbox.io/p/sandbox/green-silence-6z7yg7?file=%2Fsrc%2FApp.js%3A13%2C3)

**Comment by hjkcai** [comment] 2023-10-18 13:34
@BumbleAd  Could you please open another issue to discuss about this bug?  I'd like to close this one

**Closed by hjkcai** 2023-10-18 13:34 UTC
